version: '3.8'

services:
  streamsets:
    image: streamsets/datacollector:4.0.1
    container_name: streamsets
    platform: linux/amd64
    ports:
      - "18630:18630"
    networks:
      - mssql-network
    environment:
      - SDC_CONF_HTTP_PORT=18630
    volumes:
      - ./streamsets_data:/data
      - ./streamsets_logs:/logs
      - ./streamsets_external_libraries:/opt/streamsets-datacollector/external-libraries
volumes:
  streamsets_data:
  streamsets_logs:

networks:
  mssql-network:
    external: true